name: CI Pipe

env:
  DOTNET_VERSION: '8.0.x'

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'uat'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'uat'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore
       
      - name: build
        run: dotnet build --no-restore